"""empty message

Revision ID: 560f5b030416
Revises: a2c88ed3a94a
Create Date: 2016-05-09 12:09:09.739649

"""

# revision identifiers, used by Alembic.
revision = '560f5b030416'
down_revision = 'a2c88ed3a94a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy_searchable import sync_trigger
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    op.create_index('ix_note_search_vector', 'note', ['search_vector'], unique=False, postgresql_using='gin')

    sync_trigger(op.get_bind(), 'note', 'search_vector', ['content'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_note_search_vector', table_name='note')
    op.drop_column('note', 'search_vector')

    sync_trigger(op.get_bind(), 'note', 'search_vector', ['content'])
    ### end Alembic commands ###
